[book]
authors = ["but212"]
language = "en"
src = "docs"
title = "Rustica"

[output.html]
default-theme = "light"
preferred-dark-theme = "coal"
git-repository-url = "https://github.com/but212/rustica"
git-repository-icon = "fab-github"
