[package]
name = "rustica"
version = "0.5.4"
authors = ["jeong-il suk <wjddlf211@naver.com>"]
edition = "2021"
description = "Rustica is a functional programming library for the Rust language."
license = "Apache-2.0"
repository = "https://github.com/but212/rustica"
readme = "README.md"

[dependencies]
futures = { version = "0.3", optional = true }
rayon = "1.10.0"
smallvec = "1.14.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"], optional = true }

[dev-dependencies]
quickcheck = "1.0"
quickcheck_macros = "1.0"
criterion = { version = "0.5", features = ["html_reports"] }

[features]
default = []
async = ["futures", "tokio"]
advanced = []
transformers = []
full = ["async", "advanced", "transformers"]

[package.metadata.docs.rs]
all-features = true

[[bench]]
name = "datatypes_benchmarks"
harness = false
