[package]
name = "rustica"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
futures = "0.3"
tokio = { version = "1", features = ["full"] }
pin-project-lite = "0.2"
pin-project = "1.1"