[package]
name = "rustica"
version = "0.4.0"
authors = ["jeong-il suk <wjddlf211@naver.com>"]
edition = "2021"
description = "Rustica is a functional programming library for the Rust language."
license = "Apache-2.0"
repository = "https://github.com/but212/rustica"
readme = "README.md"

[dependencies]
futures = "0.3"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }

[dev-dependencies]
quickcheck = "1.0"
quickcheck_macros = "1.0"