[package]
name = "rustica"
version = "0.2.0"
authors = ["jeong-il suk <wjddlf211@naver.com>"]
edition = "2021"
description = "Rustica is a functional programming library for the Rust language."
license = "Apache-2.0"
repository = "https://github.com/but212/rustica"
readme = "README.md"

[dependencies]
async-trait = "0.1"
futures = "0.3"
tokio = { version = "1", features = ["full"] }
pin-project-lite = "0.2"
pin-project = "1.1"