disallowed-methods = []
too-many-arguments-threshold = 5
type-complexity-threshold = 150
enum-variant-size-threshold = 100

# Cognitive complexity tuned for maintainability
cognitive-complexity-threshold = 15

# Documentation-related configurations
doc-valid-idents = ["PersistentVector", "HKT", "Functor", "Applicative", "Monad", "fmap", "Monoid", "Semigroup", "Foldable"]

# Reasonable defaults for type and array sizes
array-size-threshold = 8
large-error-threshold = 100
verbose-bit-mask-threshold = 1

# Restrict nesting for clarity
excessive-nesting-threshold = 4

# Disallowed types that should never be used in this codebase
disallowed-types = [
    # Add types that should never be used in the codebase
]

# Disallowed names to avoid in code
disallowed-names = [
    # Add names that should be avoided
]

# Custom configuration for checking private items
check-private-items = true

# Additional documentation enforcement
missing-docs-in-crate-items = true

# Stricter lines threshold for readability
too-many-lines-threshold = 150