edition = "2021"
max_width = 100
tab_spaces = 4
newline_style = "Auto"
use_small_heuristics = "Default"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
use_field_init_shorthand = true
fn_params_layout = "Compressed"
match_arm_leading_pipes = "Preserve"
match_block_trailing_comma = true
