name: Rust Benchmarks

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  # Allow manual trigger
  workflow_dispatch:
    inputs:
      benchmark_type:
        description: 'Type of benchmark to run'
        required: true
        default: 'core'
        type: choice
        options:
          - core
          - all

jobs:
  benchmark:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Run core benchmarks (default)
        if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.benchmark_type == 'core' }}
        run: cargo bench --features advanced -- "either|id|choice|maybe"
        
      - name: Run all benchmarks
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.benchmark_type == 'all' }}
        run: cargo bench --features advanced
        
      - name: Save benchmark results
        run: |
          mkdir -p benchmark-results
          cp -r target/criterion benchmark-results/
      
      - name: Deploy benchmark results to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./benchmark-results
          keep_files: true
          publish_branch: gh-pages
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Update benchmark results'
