name: Code Quality

permissions:
  contents: read
  statuses: write
  checks: write
  pull-requests: write

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  formatting:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt
      
      - name: Check formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
  
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Install minimal profile for develop branch
      - name: Install minimal toolchain (develop branch)
        if: github.ref == 'refs/heads/develop'
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy
      
      # Install full profile for main branch
      - name: Install full toolchain (main branch)
        if: github.ref == 'refs/heads/main'
        uses: actions-rs/toolchain@v1
        with:
          profile: complete
          toolchain: stable
          override: true
          components: clippy
      
      # Run clippy with appropriate features based on branch
      - name: Clippy with minimal features (develop)
        if: github.ref == 'refs/heads/develop'
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
      
      - name: Clippy with full features (main)
        if: github.ref == 'refs/heads/main'
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --features=full -- -D warnings
  
  doc-test:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Install minimal profile for develop branch
      - name: Install minimal toolchain (develop branch)
        if: github.ref == 'refs/heads/develop'
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      
      # Install full profile for main branch
      - name: Install full toolchain (main branch)
        if: github.ref == 'refs/heads/main'
        uses: actions-rs/toolchain@v1
        with:
          profile: complete
          toolchain: stable
          override: true
      
      # Check documentation with appropriate features based on branch
      - name: Check documentation builds (develop)
        if: github.ref == 'refs/heads/develop'
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --no-deps
      
      - name: Check documentation builds (main)
        if: github.ref == 'refs/heads/main'
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --no-deps --features=full
      
      - name: Check dead links
        uses: actions-rs/cargo@v1
        with:
          command: rustdoc
          args: -- -D warnings
  
  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Install minimal profile for develop branch
      - name: Install minimal toolchain (develop branch)
        if: github.ref == 'refs/heads/develop'
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      
      # Install full profile for main branch
      - name: Install full toolchain (main branch)
        if: github.ref == 'refs/heads/main'
        uses: actions-rs/toolchain@v1
        with:
          profile: complete
          toolchain: stable
          override: true
      
      - name: Install cargo-audit
        run: cargo install cargo-audit
      
      - name: Run security audit
        run: cargo audit